# Generated by Django 4.1 on 2022-11-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shareCode",
                    models.CharField(max_length=10, verbose_name="shareCode"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("openingPrice", models.FloatField(verbose_name="openingPrice")),
                ("highestPrice", models.FloatField(verbose_name="highestPrice")),
                ("lowestPrice", models.FloatField(verbose_name="lowestPrice")),
                ("closingPrice", models.FloatField(verbose_name="closingPrice")),
                ("priceDifferent", models.FloatField(verbose_name="priceDifferent")),
                (
                    "PriceDifferentPercentage",
                    models.FloatField(verbose_name="PriceDifferentPercentage"),
                ),
                ("TradingVolume", models.FloatField(verbose_name="TradingVolume")),
                ("Amount", models.FloatField(verbose_name="Amount")),
                ("StockAmplitude", models.FloatField(verbose_name="StockAmplitude")),
                ("TurnoverRate", models.FloatField(verbose_name="TurnoverRate")),
            ],
        ),
        migrations.CreateModel(
            name="marketValue",
            fields=[
                (
                    "shareCode",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="shareCode",
                    ),
                ),
                ("value", models.FloatField(verbose_name="value(100 million)")),
            ],
        ),
        migrations.CreateModel(
            name="stock",
            fields=[
                (
                    "shareCode",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="shareCode",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="name")),
                ("area", models.CharField(max_length=10, verbose_name="area")),
                ("industry", models.CharField(max_length=10, verbose_name="industry")),
                ("market", models.CharField(max_length=10, verbose_name="market")),
                ("listDate", models.CharField(max_length=10, verbose_name="listDate")),
            ],
        ),
    ]
