# Generated by Django 4.1 on 2022-11-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketvalue",
            name="value",
            field=models.FloatField(default=0, verbose_name="value(100 million)"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="area",
            field=models.CharField(max_length=10, null=True, verbose_name="area"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="industry",
            field=models.CharField(max_length=10, null=True, verbose_name="industry"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="market",
            field=models.CharField(max_length=10, null=True, verbose_name="market"),
        ),
    ]
