# Generated by Django 4.1 on 2022-11-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echart", "0002_alter_marketvalue_value_alter_stock_area_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="marketValue",),
        migrations.AddField(
            model_name="stock",
            name="value",
            field=models.FloatField(default=0, verbose_name="value(100 million)"),
        ),
    ]
