# Generated by Django 4.1 on 2022-11-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("echart", "0004_alter_stock_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="value",
            field=models.FloatField(default=0, verbose_name="value(100 million)"),
        ),
    ]
